load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//tools/bazel:rust_defs.bzl", "RUST_2021")

rust_library(
    name = "niconeon-filter",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "niconeon_filter",
    crate_root = "src/lib.rs",
    edition = RUST_2021,
    visibility = ["//core:__subpackages__"],
    deps = [
        "//core/crates/niconeon-domain",
        "@crates//:chrono",
        "@crates//:regex",
        "@crates//:thiserror",
    ],
)

rust_test(
    name = "unit_test",
    crate = ":niconeon-filter",
    deps = [
        "//core/crates/niconeon-domain",
        "@crates//:chrono",
        "@crates//:regex",
        "@crates//:thiserror",
    ],
)
