add_library(niconeon_options INTERFACE)
target_compile_features(niconeon_options INTERFACE cxx_std_23)
if(WIN32)
  target_compile_definitions(niconeon_options INTERFACE NOMINMAX WIN32_LEAN_AND_MEAN)
endif()
if(MSVC)
  target_compile_options(niconeon_options INTERFACE /W4 /permissive- /utf-8)
else()
  target_compile_options(niconeon_options INTERFACE -Wall -Wextra -Wpedantic)
endif()
option(NICONEON_WARNINGS_AS_ERRORS "Treat project compiler warnings as errors" OFF)
if(NICONEON_WARNINGS_AS_ERRORS)
  if(MSVC)
    target_compile_options(niconeon_options INTERFACE /WX)
  else()
    target_compile_options(niconeon_options INTERFACE -Werror)
  endif()
endif()
set(NICONEON_SANITIZERS "" CACHE STRING "Sanitizers: empty, address,undefined, or thread")
if(NICONEON_SANITIZERS)
  if(WIN32 OR MSVC)
    message(FATAL_ERROR "The sanitizer presets are supported on Linux with GCC or Clang")
  endif()
  if(NICONEON_SANITIZERS MATCHES "thread" AND NICONEON_SANITIZERS MATCHES "address")
    message(FATAL_ERROR "ThreadSanitizer and AddressSanitizer cannot be combined")
  endif()
  target_compile_options(niconeon_options INTERFACE "-fsanitize=${NICONEON_SANITIZERS}" -fno-omit-frame-pointer)
  target_link_options(niconeon_options INTERFACE "-fsanitize=${NICONEON_SANITIZERS}" -fno-omit-frame-pointer)
endif()
option(NICONEON_CLANG_TIDY "Run clang-tidy during compilation" OFF)
if(NICONEON_CLANG_TIDY)
  find_program(CLANG_TIDY_EXECUTABLE NAMES clang-tidy-19 clang-tidy REQUIRED)
  set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY_EXECUTABLE};--quiet")
endif()
